chat_format: '&3%player%: &7%message%'
blockbreak_message: '&cYou may not break blocks on hub.'
blockplace_message: '&cYou may not place blocks on hub.'
quit_message: '&7[&a+&7] &a%player%'
join_message: '&7[&c-&7] &c%player%'
staffjoin_message: '&7[&3Staff&7] &a%player%'
staffquit_message: '&7[&3Staff&7] &c%player%'
discord_message: '&3Discord: &bSorex.com/discord'
ts_message: '&3TeamSpeak: &bSorex.com/teamspeak'
twitter_message: '&3Twitter: &bTwitter.com/Sorex'
nopermission_chat: '&3Buy rank at &bSorex.com/store &3in order to speak in chat.'
